// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfz5Z1xudZwq864svLpomUMmYZECRy40',
    appId: '1:233079952728:web:6e2655af82ded1006d412d',
    messagingSenderId: '233079952728',
    projectId: 'geo-tracker-3ee3a',
    authDomain: 'geo-tracker-3ee3a.firebaseapp.com',
    storageBucket: 'geo-tracker-3ee3a.appspot.com',
    measurementId: 'G-SE2H6J2YGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_p4swWdoGMq9h6che5Wsz28h2utdVh2M',
    appId: '1:233079952728:android:f0d3efc3f12d08846d412d',
    messagingSenderId: '233079952728',
    projectId: 'geo-tracker-3ee3a',
    storageBucket: 'geo-tracker-3ee3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2scbBtJSZoCWek_HsBWlF5oWeL857N94',
    appId: '1:233079952728:ios:bfa543a31f9bfb8c6d412d',
    messagingSenderId: '233079952728',
    projectId: 'geo-tracker-3ee3a',
    storageBucket: 'geo-tracker-3ee3a.appspot.com',
    iosClientId: '233079952728-bgda05ebjrqdensmf7ecrsjtqipc06j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2scbBtJSZoCWek_HsBWlF5oWeL857N94',
    appId: '1:233079952728:ios:bfa543a31f9bfb8c6d412d',
    messagingSenderId: '233079952728',
    projectId: 'geo-tracker-3ee3a',
    storageBucket: 'geo-tracker-3ee3a.appspot.com',
    iosClientId: '233079952728-bgda05ebjrqdensmf7ecrsjtqipc06j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoTracker',
  );
}
